#ifndef BUTTONS_H
#define BUTTONS_H

#include <SDL_mouse.h>

enum EButton {
    BUTTON_LEFT = SDL_BUTTON_LEFT,
    BUTTON_MIDDLE = SDL_BUTTON_MIDDLE,
    BUTTON_RIGHT = SDL_BUTTON_RIGHT,
    BUTTON_BACK = SDL_BUTTON_X1,
    BUTTON_FORWARD = SDL_BUTTON_X2
};

#endif
