#ifndef INPUT_H
#define INPUT_H

enum EButton {
    JARP_BUTTON_UNKNOWN = 0,
    JARP_BUTTON_LEFT,
    JARP_BUTTON_MIDDLE,
    JARP_BUTTON_RIGHT,
    JARP_BUTTON_BACK,
    JARP_BUTTON_FORWARD,

    JARP_BUTTON_COUNT = 16
};

enum EKey {
    JARP_KEY_UNKNOWN = 0,

    JARP_KEY_A,
    JARP_KEY_D,
    JARP_KEY_S,
    JARP_KEY_W,
    JARP_KEY_SPACE,
    JARP_KEY_LEFT,
    JARP_KEY_RIGHT,

    JARP_KEY_COUNT = 512
};

#endif
