#ifndef KEYS_H
#define KEYS_H

#include <SDL_scancode.h>

enum EKey {
    KEY_UNKNOWN = SDL_SCANCODE_UNKNOWN,

    KEY_W = SDL_SCANCODE_W,
    KEY_A = SDL_SCANCODE_A,
    KEY_S = SDL_SCANCODE_S,
    KEY_D = SDL_SCANCODE_D,
    KEY_SPACE = SDL_SCANCODE_SPACE,

    KEY_LEFT = SDL_SCANCODE_LEFT,
    KEY_RIGHT = SDL_SCANCODE_RIGHT,

    KEY_COUNT = SDL_NUM_SCANCODES
};

#endif
